apiVersion: v1
kind: Service
metadata:
  name: unguard-status-service
  labels:
    app.kubernetes.io/name: status-service
    app.kubernetes.io/part-of: unguard
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: status-service
    app.kubernetes.io/part-of: unguard
  ports:
    - targetPort: 8083
      port: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unguard-status
  labels:
    app.kubernetes.io/name: status-service
    app.kubernetes.io/part-of: unguard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: status-role
  labels:
    app.kubernetes.io/name: status-service
    app.kubernetes.io/part-of: unguard
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: ["get", "list" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: status-rolebinding
  labels:
    app.kubernetes.io/name: status-service
    app.kubernetes.io/part-of: unguard
subjects:
  - kind: ServiceAccount
    name: unguard-status
    apiGroup: ""
roleRef:
  kind: Role
  name: status-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-status-service
  labels:
    app.kubernetes.io/name: status-service
    app.kubernetes.io/part-of: unguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: status-service
      app.kubernetes.io/part-of: unguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: status-service
        app.kubernetes.io/part-of: unguard
    spec:
      serviceAccountName: unguard-status
      containers:
        - name: status-service
          image: {{ .Values.unguard.statusService.image }}:{{ .Values.unguard.statusService.tag }}
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: API_PATH
              value: "/status-service"
            - name: KUBERNETES_NAMESPACE
              value: "unguard"
            - name: IGNORED_DEPLOYMENTS # add deployments to ignore separated by spaces
              value: "unguard-user-simulator"
            - name: DT_RELEASE_VERSION
              value: "{{ .Values.unguard.adService.tag }}"
            - name: DT_RELEASE_BUILD_VERSION
              value: "{{ .Values.unguard.adService.tag }}"
            - name: DT_RELEASE_PRODUCT
              value: "{{ .Chart.Name }}"
            - name: DT_RELEASE_STAGE
              value: "{{ .Release.Namespace }}"    
